server:
  port: 7001

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    register-with-eureka: true  #服务注册开关
    fetch-registry: true  #服务发现开关
    service-url:  #注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #指定实例ID，页面会显示主机名
    prefer-ip-address: true #访问路径可以显示ip地址

zuul: # 网关配置
  sensitive-headers: null # 默认Zuul认为请求头中 "Cookie", "Set-Cookie", "Authorization" 是敏感信息，它不会转发 请求，因为把它设置为空，就会转发了
  add-host-header: true # 正确的处理重定向操作
  routes:
    authentication: # 路由名称，名称任意，保持所有路由名称唯一
      path: /auth/** # 访问路径，转发到 auth-server 服务处理
      serviceId: auth-server # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
    product: # 商品服务路由配置
      path: /product/** # 转发到 product-server 服务处理
      serviceId: product-server
      stripPrefix: false