server:
  port: 8080

eureka:
  client:
    register-with-eureka: true  #服务注册开关
    fetch-registry: true  #服务发现开关
    service-url:  #注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #指定实例ID，页面会显示主机名
    prefer-ip-address: true #访问路径可以显示ip地址

spring:
  application:
    name: product-server #Eureka页面显示